### ISSUE TITLE
OSP14 doesn't create a ssh keypair for root on the undercloud

### ISSUE THREAD

**Issue by dsavineau** [redhat-cip/dci-openstack-agent#1]
OSP14 doesn't create a ssh keypair for root on the undercloud so the key setup between root@undercloud and heat-admin@overcloud[0] (1) breaks the workflow prior the certification.

```console
# Fetch the root pub key
file not found: /root/.ssh/id_rsa.pub
```

(1) https://github.com/redhat-cip/dci-openstack-agent/blob/master/plays/run_tests.yml#L73-L85

**Comment by goneri** [comment]
I suggest: https://softwarefactory-project.io/r/#/c/13896/
