### ISSUE TITLE
Http(s) Proxy when downloading the images list file

### ISSUE THREAD

**Issue by sjabasti** [redhat-cip/dci-openstack-agent#9]
**File**: dci-openstack-agent/plays/fetch_bits.yml 
**Task**: Download the images list file
**Overview**: Task timeouts when run behind a proxy
**Problem**: The task uses "get_url" together with "become yes". This step thus ignores the http_proxy environment variable.
**Possible workaround**:  Add to documentation that sudoers should keep the http_proxy environment by adding the line: `Defaults    env_keep += "http_proxy https_proxy"`  to /etc/sudoers after the line `Defaults    env_keep ="`

**Comment by fcharlier** [comment]
@sjabasti thanks for reporting this issue.

Although changing the sudoers setting works, I'd like to verify if we could just not use `become: true` to download all these files before changing the documentation.

**Comment by sjabasti** [comment]
I agree, if it can be avoided to downloading files as root, it should be avoided. it should not be downloading files as root. (do note this bug was filed a few months ago, and i cant remember if there was a reason the tasks needed to be root)

**Comment by fcharlier** [comment]
Okay, after a quick glance,, we're currently using reposync/yum to download the RHOSP repository and this is executed as root in the [ansible-role-dci-retrieve-component](https://github.com/redhat-cip/ansible-role-dci-retrieve-component/blob/master/tasks/sync_repo.yml#L58-L65) role.

I need to verify if it could be executed as simple user.

**Comment by fcharlier** [comment]
Fixed in 3c29ffb6fdfd23d
